title: CosmoEmbeddings
description: A decentralized semantic network for AIs built on embeddings
theme: jekyll-theme-minimal
baseurl: "/CosmoEmbeddings"
url: "https://armandojaleo.github.io"

# Build settings
markdown: kramdown
permalink: pretty

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - .github/
  - .gitignore 